version: '3.9'

services:
  web:
    container_name: web
    image: harbor.singu.dev/web/web:latest
    ports:
      - 80:80
    networks:
      - npm
      
networks:
  npm:
    name: npm
    external: true
